//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWPF.ProxyWCFNormal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order_Detail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Category))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order_Detail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Category))]
    public partial class EntityObject : ClienteWPF.ProxyWCFNormal.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Product : ClienteWPF.ProxyWCFNormal.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiscontinuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityPerUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.Category RelCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.EntityReferenceOfCategory7Zl6WYH6 RelCategoryReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.Order_Detail[] RelOrder_DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ReorderLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> UnitsInStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> UnitsOnOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Discontinued {
            get {
                return this.DiscontinuedField;
            }
            set {
                if ((this.DiscontinuedField.Equals(value) != true)) {
                    this.DiscontinuedField = value;
                    this.RaisePropertyChanged("Discontinued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityPerUnit {
            get {
                return this.QuantityPerUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityPerUnitField, value) != true)) {
                    this.QuantityPerUnitField = value;
                    this.RaisePropertyChanged("QuantityPerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.Category RelCategory {
            get {
                return this.RelCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.RelCategoryField, value) != true)) {
                    this.RelCategoryField = value;
                    this.RaisePropertyChanged("RelCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.EntityReferenceOfCategory7Zl6WYH6 RelCategoryReference {
            get {
                return this.RelCategoryReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RelCategoryReferenceField, value) != true)) {
                    this.RelCategoryReferenceField = value;
                    this.RaisePropertyChanged("RelCategoryReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.Order_Detail[] RelOrder_Details {
            get {
                return this.RelOrder_DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelOrder_DetailsField, value) != true)) {
                    this.RelOrder_DetailsField = value;
                    this.RaisePropertyChanged("RelOrder_Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ReorderLevel {
            get {
                return this.ReorderLevelField;
            }
            set {
                if ((this.ReorderLevelField.Equals(value) != true)) {
                    this.ReorderLevelField = value;
                    this.RaisePropertyChanged("ReorderLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> UnitsInStock {
            get {
                return this.UnitsInStockField;
            }
            set {
                if ((this.UnitsInStockField.Equals(value) != true)) {
                    this.UnitsInStockField = value;
                    this.RaisePropertyChanged("UnitsInStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> UnitsOnOrder {
            get {
                return this.UnitsOnOrderField;
            }
            set {
                if ((this.UnitsOnOrderField.Equals(value) != true)) {
                    this.UnitsOnOrderField = value;
                    this.RaisePropertyChanged("UnitsOnOrder");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order_Detail", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Order_Detail : ClienteWPF.ProxyWCFNormal.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.Order RelOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.EntityReferenceOfOrder7Zl6WYH6 RelOrderReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.Product RelProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.EntityReferenceOfProduct7Zl6WYH6 RelProductReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.Order RelOrder {
            get {
                return this.RelOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.RelOrderField, value) != true)) {
                    this.RelOrderField = value;
                    this.RaisePropertyChanged("RelOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.EntityReferenceOfOrder7Zl6WYH6 RelOrderReference {
            get {
                return this.RelOrderReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RelOrderReferenceField, value) != true)) {
                    this.RelOrderReferenceField = value;
                    this.RaisePropertyChanged("RelOrderReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.Product RelProduct {
            get {
                return this.RelProductField;
            }
            set {
                if ((object.ReferenceEquals(this.RelProductField, value) != true)) {
                    this.RelProductField = value;
                    this.RaisePropertyChanged("RelProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.EntityReferenceOfProduct7Zl6WYH6 RelProductReference {
            get {
                return this.RelProductReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RelProductReferenceField, value) != true)) {
                    this.RelProductReferenceField = value;
                    this.RaisePropertyChanged("RelProductReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Order : ClienteWPF.ProxyWCFNormal.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.Order_Detail[] RelOrder_DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RequiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShipViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShippedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Freight {
            get {
                return this.FreightField;
            }
            set {
                if ((this.FreightField.Equals(value) != true)) {
                    this.FreightField = value;
                    this.RaisePropertyChanged("Freight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.Order_Detail[] RelOrder_Details {
            get {
                return this.RelOrder_DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelOrder_DetailsField, value) != true)) {
                    this.RelOrder_DetailsField = value;
                    this.RaisePropertyChanged("RelOrder_Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RequiredDate {
            get {
                return this.RequiredDateField;
            }
            set {
                if ((this.RequiredDateField.Equals(value) != true)) {
                    this.RequiredDateField = value;
                    this.RaisePropertyChanged("RequiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipAddress {
            get {
                return this.ShipAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipAddressField, value) != true)) {
                    this.ShipAddressField = value;
                    this.RaisePropertyChanged("ShipAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCity {
            get {
                return this.ShipCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCityField, value) != true)) {
                    this.ShipCityField = value;
                    this.RaisePropertyChanged("ShipCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCountry {
            get {
                return this.ShipCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCountryField, value) != true)) {
                    this.ShipCountryField = value;
                    this.RaisePropertyChanged("ShipCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipName {
            get {
                return this.ShipNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipNameField, value) != true)) {
                    this.ShipNameField = value;
                    this.RaisePropertyChanged("ShipName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipPostalCode {
            get {
                return this.ShipPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipPostalCodeField, value) != true)) {
                    this.ShipPostalCodeField = value;
                    this.RaisePropertyChanged("ShipPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipRegion {
            get {
                return this.ShipRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipRegionField, value) != true)) {
                    this.ShipRegionField = value;
                    this.RaisePropertyChanged("ShipRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShipVia {
            get {
                return this.ShipViaField;
            }
            set {
                if ((this.ShipViaField.Equals(value) != true)) {
                    this.ShipViaField = value;
                    this.RaisePropertyChanged("ShipVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippedDate {
            get {
                return this.ShippedDateField;
            }
            set {
                if ((this.ShippedDateField.Equals(value) != true)) {
                    this.ShippedDateField = value;
                    this.RaisePropertyChanged("ShippedDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Category : ClienteWPF.ProxyWCFNormal.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.Product[] RelProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.Product[] RelProducts {
            get {
                return this.RelProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelProductsField, value) != true)) {
                    this.RelProductsField = value;
                    this.RaisePropertyChanged("RelProducts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfCategory7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfOrder7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfProduct7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Product[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order_Detail[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order_Detail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.Order[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.ClaseError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.enumTipoError))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCategory7Zl6WYH6", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfCategory7Zl6WYH6 : ClienteWPF.ProxyWCFNormal.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfOrder7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfProduct7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfCategory7Zl6WYH6))]
    public partial class EntityReference : ClienteWPF.ProxyWCFNormal.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfOrder7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfProduct7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWPF.ProxyWCFNormal.EntityReferenceOfCategory7Zl6WYH6))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfOrder7Zl6WYH6", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfOrder7Zl6WYH6 : ClienteWPF.ProxyWCFNormal.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProduct7Zl6WYH6", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfProduct7Zl6WYH6 : ClienteWPF.ProxyWCFNormal.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaseError", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.SerializableAttribute()]
    public partial class ClaseError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWPF.ProxyWCFNormal.enumTipoError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Datos {
            get {
                return this.DatosField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosField, value) != true)) {
                    this.DatosField = value;
                    this.RaisePropertyChanged("Datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWPF.ProxyWCFNormal.enumTipoError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enumTipoError", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    public enum enumTipoError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CategoriaNoEncontrada = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CategoriaErronea = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Otros = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.miempresa.wwww", ConfigurationName="ProxyWCFNormal.IServicioNormal")]
    public interface IServicioNormal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/GetData", ReplyAction="http://com.miempresa.wwww/IServicioNormal/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorID", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDResponse")]
        ClienteWPF.ProxyWCFNormal.Category CategoriaPorID(int cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/ProductosPorCategoria", ReplyAction="http://com.miempresa.wwww/IServicioNormal/ProductosPorCategoriaResponse")]
        ClienteWPF.ProxyWCFNormal.Product[] ProductosPorCategoria(int IdCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaYProductosPorId", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaYProductosPorIdResponse")]
        ClienteWPF.ProxyWCFNormal.Category CategoriaYProductosPorId(int cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/PedidoPorCliente", ReplyAction="http://com.miempresa.wwww/IServicioNormal/PedidoPorClienteResponse")]
        ClienteWPF.ProxyWCFNormal.Order PedidoPorCliente(string Cliente, int Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/PedidosPorCliente", ReplyAction="http://com.miempresa.wwww/IServicioNormal/PedidosPorClienteResponse")]
        ClienteWPF.ProxyWCFNormal.Order[] PedidosPorCliente(string Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErrores", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErroresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErroresStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteWPF.ProxyWCFNormal.ClaseError), Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErroresClaseErrorFault" +
            "", Name="ClaseError", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
        ClienteWPF.ProxyWCFNormal.Category CategoriaPorIDConErrores(int IdCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDconPausa", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDconPausaResponse")]
        ClienteWPF.ProxyWCFNormal.Category CategoriaPorIDconPausa(int IdCategoria, int segundos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioNormalChannel : ClienteWPF.ProxyWCFNormal.IServicioNormal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioNormalClient : System.ServiceModel.ClientBase<ClienteWPF.ProxyWCFNormal.IServicioNormal>, ClienteWPF.ProxyWCFNormal.IServicioNormal {
        
        public ServicioNormalClient() {
        }
        
        public ServicioNormalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioNormalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNormalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNormalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public ClienteWPF.ProxyWCFNormal.Category CategoriaPorID(int cat) {
            return base.Channel.CategoriaPorID(cat);
        }
        
        public ClienteWPF.ProxyWCFNormal.Product[] ProductosPorCategoria(int IdCategoria) {
            return base.Channel.ProductosPorCategoria(IdCategoria);
        }
        
        public ClienteWPF.ProxyWCFNormal.Category CategoriaYProductosPorId(int cat) {
            return base.Channel.CategoriaYProductosPorId(cat);
        }
        
        public ClienteWPF.ProxyWCFNormal.Order PedidoPorCliente(string Cliente, int Pedido) {
            return base.Channel.PedidoPorCliente(Cliente, Pedido);
        }
        
        public ClienteWPF.ProxyWCFNormal.Order[] PedidosPorCliente(string Cliente) {
            return base.Channel.PedidosPorCliente(Cliente);
        }
        
        public ClienteWPF.ProxyWCFNormal.Category CategoriaPorIDConErrores(int IdCategoria) {
            return base.Channel.CategoriaPorIDConErrores(IdCategoria);
        }
        
        public ClienteWPF.ProxyWCFNormal.Category CategoriaPorIDconPausa(int IdCategoria, int segundos) {
            return base.Channel.CategoriaPorIDconPausa(IdCategoria, segundos);
        }
    }
}
