//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWPF.ProxyPorSesion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPorSesion.IServicioPorSesion")]
    public interface IServicioPorSesion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/IncrementaContador", ReplyAction="http://tempuri.org/IServicioGeneral/IncrementaContadorResponse")]
        int IncrementaContador(int segundosParada);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPorSesionChannel : ClienteWPF.ProxyPorSesion.IServicioPorSesion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPorSesionClient : System.ServiceModel.ClientBase<ClienteWPF.ProxyPorSesion.IServicioPorSesion>, ClienteWPF.ProxyPorSesion.IServicioPorSesion {
        
        public ServicioPorSesionClient() {
        }
        
        public ServicioPorSesionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPorSesionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPorSesionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPorSesionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int IncrementaContador(int segundosParada) {
            return base.Channel.IncrementaContador(segundosParada);
        }
    }
}
