//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.Objects.DataClasses
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order_Detail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Category))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order_Detail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Category))]
    public partial class EntityObject : System.Data.Objects.DataClasses.StructuralObject
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCategory7Zl6WYH6", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfCategory7Zl6WYH6 : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfOrder7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProduct7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCategory7Zl6WYH6))]
    public partial class EntityReference : System.Data.Objects.DataClasses.RelatedEnd
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfOrder7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProduct7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCategory7Zl6WYH6))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfOrder7Zl6WYH6", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfOrder7Zl6WYH6 : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProduct7Zl6WYH6", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfProduct7Zl6WYH6 : System.Data.Objects.DataClasses.EntityReference
    {
    }
}
namespace ServiciosWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    public partial class Product : System.Data.Objects.DataClasses.EntityObject
    {
        
        private System.Nullable<int> CategoryIDField;
        
        private bool DiscontinuedField;
        
        private int ProductIDField;
        
        private string ProductNameField;
        
        private string QuantityPerUnitField;
        
        private ServiciosWCF.Category RelCategoryField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfCategory7Zl6WYH6 RelCategoryReferenceField;
        
        private ServiciosWCF.Order_Detail[] RelOrder_DetailsField;
        
        private System.Nullable<short> ReorderLevelField;
        
        private System.Nullable<int> SupplierIDField;
        
        private System.Nullable<decimal> UnitPriceField;
        
        private System.Nullable<short> UnitsInStockField;
        
        private System.Nullable<short> UnitsOnOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Discontinued
        {
            get
            {
                return this.DiscontinuedField;
            }
            set
            {
                this.DiscontinuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityPerUnit
        {
            get
            {
                return this.QuantityPerUnitField;
            }
            set
            {
                this.QuantityPerUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosWCF.Category RelCategory
        {
            get
            {
                return this.RelCategoryField;
            }
            set
            {
                this.RelCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfCategory7Zl6WYH6 RelCategoryReference
        {
            get
            {
                return this.RelCategoryReferenceField;
            }
            set
            {
                this.RelCategoryReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosWCF.Order_Detail[] RelOrder_Details
        {
            get
            {
                return this.RelOrder_DetailsField;
            }
            set
            {
                this.RelOrder_DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ReorderLevel
        {
            get
            {
                return this.ReorderLevelField;
            }
            set
            {
                this.ReorderLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SupplierID
        {
            get
            {
                return this.SupplierIDField;
            }
            set
            {
                this.SupplierIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> UnitsInStock
        {
            get
            {
                return this.UnitsInStockField;
            }
            set
            {
                this.UnitsInStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> UnitsOnOrder
        {
            get
            {
                return this.UnitsOnOrderField;
            }
            set
            {
                this.UnitsOnOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order_Detail", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    public partial class Order_Detail : System.Data.Objects.DataClasses.EntityObject
    {
        
        private float DiscountField;
        
        private int OrderIDField;
        
        private int ProductIDField;
        
        private short QuantityField;
        
        private ServiciosWCF.Order RelOrderField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfOrder7Zl6WYH6 RelOrderReferenceField;
        
        private ServiciosWCF.Product RelProductField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfProduct7Zl6WYH6 RelProductReferenceField;
        
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosWCF.Order RelOrder
        {
            get
            {
                return this.RelOrderField;
            }
            set
            {
                this.RelOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfOrder7Zl6WYH6 RelOrderReference
        {
            get
            {
                return this.RelOrderReferenceField;
            }
            set
            {
                this.RelOrderReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosWCF.Product RelProduct
        {
            get
            {
                return this.RelProductField;
            }
            set
            {
                this.RelProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfProduct7Zl6WYH6 RelProductReference
        {
            get
            {
                return this.RelProductReferenceField;
            }
            set
            {
                this.RelProductReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    public partial class Order : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string CustomerIDField;
        
        private System.Nullable<int> EmployeeIDField;
        
        private System.Nullable<decimal> FreightField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        private int OrderIDField;
        
        private ServiciosWCF.Order_Detail[] RelOrder_DetailsField;
        
        private System.Nullable<System.DateTime> RequiredDateField;
        
        private string ShipAddressField;
        
        private string ShipCityField;
        
        private string ShipCountryField;
        
        private string ShipNameField;
        
        private string ShipPostalCodeField;
        
        private string ShipRegionField;
        
        private System.Nullable<int> ShipViaField;
        
        private System.Nullable<System.DateTime> ShippedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                this.EmployeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Freight
        {
            get
            {
                return this.FreightField;
            }
            set
            {
                this.FreightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosWCF.Order_Detail[] RelOrder_Details
        {
            get
            {
                return this.RelOrder_DetailsField;
            }
            set
            {
                this.RelOrder_DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RequiredDate
        {
            get
            {
                return this.RequiredDateField;
            }
            set
            {
                this.RequiredDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipAddress
        {
            get
            {
                return this.ShipAddressField;
            }
            set
            {
                this.ShipAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCity
        {
            get
            {
                return this.ShipCityField;
            }
            set
            {
                this.ShipCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCountry
        {
            get
            {
                return this.ShipCountryField;
            }
            set
            {
                this.ShipCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipName
        {
            get
            {
                return this.ShipNameField;
            }
            set
            {
                this.ShipNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipPostalCode
        {
            get
            {
                return this.ShipPostalCodeField;
            }
            set
            {
                this.ShipPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipRegion
        {
            get
            {
                return this.ShipRegionField;
            }
            set
            {
                this.ShipRegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShipVia
        {
            get
            {
                return this.ShipViaField;
            }
            set
            {
                this.ShipViaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippedDate
        {
            get
            {
                return this.ShippedDateField;
            }
            set
            {
                this.ShippedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF", IsReference=true)]
    public partial class Category : System.Data.Objects.DataClasses.EntityObject
    {
        
        private int CategoryIDField;
        
        private string CategoryNameField;
        
        private string DescriptionField;
        
        private byte[] PictureField;
        
        private ServiciosWCF.Product[] RelProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture
        {
            get
            {
                return this.PictureField;
            }
            set
            {
                this.PictureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosWCF.Product[] RelProducts
        {
            get
            {
                return this.RelProductsField;
            }
            set
            {
                this.RelProductsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaseError", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    public partial class ClaseError : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DatosField;
        
        private ServiciosWCF.enumTipoError ErrorField;
        
        private string MensajeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosWCF.enumTipoError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enumTipoError", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    public enum enumTipoError : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CategoriaNoEncontrada = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CategoriaErronea = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Otros = 2,
    }
}
namespace System.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EntityContainerNameField;
        
        private System.Data.EntityKeyMember[] EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName
        {
            get
            {
                return this.EntityContainerNameField;
            }
            set
            {
                this.EntityContainerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKeyMember[] EntityKeyValues
        {
            get
            {
                return this.EntityKeyValuesField;
            }
            set
            {
                this.EntityKeyValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName
        {
            get
            {
                return this.EntitySetNameField;
            }
            set
            {
                this.EntitySetNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCategory7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfOrder7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProduct7Zl6WYH6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[][]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Product[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order_Detail[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order_Detail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.Order[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.ClaseError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiciosWCF.enumTipoError))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private object ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://com.miempresa2.wwww", ConfigurationName="IServicioNormalAux")]
public interface IServicioNormalAux
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa2.wwww/IServicioNormalAux/CategoriaPorID", ReplyAction="http://com.miempresa2.wwww/IServicioNormalAux/CategoriaPorIDResponse")]
    ServiciosWCF.Category CategoriaPorID(int cat);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa2.wwww/IServicioNormalAux/ProductosPorCategoria", ReplyAction="http://com.miempresa2.wwww/IServicioNormalAux/ProductosPorCategoriaResponse")]
    ServiciosWCF.Product[] ProductosPorCategoria(int IdCategoria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa2.wwww/IServicioNormalAux/Hora", ReplyAction="http://com.miempresa2.wwww/IServicioNormalAux/HoraResponse")]
    System.DateTime Hora();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServicioNormalAuxChannel : IServicioNormalAux, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServicioNormalAuxClient : System.ServiceModel.ClientBase<IServicioNormalAux>, IServicioNormalAux
{
    
    public ServicioNormalAuxClient()
    {
    }
    
    public ServicioNormalAuxClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServicioNormalAuxClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioNormalAuxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioNormalAuxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ServiciosWCF.Category CategoriaPorID(int cat)
    {
        return base.Channel.CategoriaPorID(cat);
    }
    
    public ServiciosWCF.Product[] ProductosPorCategoria(int IdCategoria)
    {
        return base.Channel.ProductosPorCategoria(IdCategoria);
    }
    
    public System.DateTime Hora()
    {
        return base.Channel.Hora();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://com.miempresa.wwww", ConfigurationName="IServicioNormal")]
public interface IServicioNormal
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/GetData", ReplyAction="http://com.miempresa.wwww/IServicioNormal/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorID", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDResponse")]
    ServiciosWCF.Category CategoriaPorID(int cat);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/ProductosPorCategoria", ReplyAction="http://com.miempresa.wwww/IServicioNormal/ProductosPorCategoriaResponse")]
    ServiciosWCF.Product[] ProductosPorCategoria(int IdCategoria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaYProductosPorId", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaYProductosPorIdResponse")]
    ServiciosWCF.Category CategoriaYProductosPorId(int cat);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/PedidoPorCliente", ReplyAction="http://com.miempresa.wwww/IServicioNormal/PedidoPorClienteResponse")]
    ServiciosWCF.Order PedidoPorCliente(string Cliente, int Pedido);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/PedidosPorCliente", ReplyAction="http://com.miempresa.wwww/IServicioNormal/PedidosPorClienteResponse")]
    ServiciosWCF.Order[] PedidosPorCliente(string Cliente);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErrores", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErroresResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ServiciosWCF.ClaseError), Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErroresClaseErrorFault" +
        "", Name="ClaseError", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDConErroresStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    ServiciosWCF.Category CategoriaPorIDConErrores(int IdCategoria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDconPausa", ReplyAction="http://com.miempresa.wwww/IServicioNormal/CategoriaPorIDconPausaResponse")]
    ServiciosWCF.Category CategoriaPorIDconPausa(int IdCategoria, int segundos);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/IncrementaContador", ReplyAction="http://com.miempresa.wwww/IServicioNormal/IncrementaContadorResponse")]
    int IncrementaContador();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com.miempresa.wwww/IServicioNormal/StockProductos", ReplyAction="http://com.miempresa.wwww/IServicioNormal/StockProductosResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCategory7Zl6WYH6))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.Objects.DataClasses.RelatedEnd))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfOrder7Zl6WYH6))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProduct7Zl6WYH6))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.EntityKeyMember))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.Category))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.Product[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.Product))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.Order_Detail[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.Order_Detail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.Order))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.Order[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.ClaseError))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiciosWCF.enumTipoError))]
    object[][] StockProductos(int IdCategoria);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServicioNormalChannel : IServicioNormal, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServicioNormalClient : System.ServiceModel.ClientBase<IServicioNormal>, IServicioNormal
{
    
    public ServicioNormalClient()
    {
    }
    
    public ServicioNormalClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServicioNormalClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioNormalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioNormalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public ServiciosWCF.Category CategoriaPorID(int cat)
    {
        return base.Channel.CategoriaPorID(cat);
    }
    
    public ServiciosWCF.Product[] ProductosPorCategoria(int IdCategoria)
    {
        return base.Channel.ProductosPorCategoria(IdCategoria);
    }
    
    public ServiciosWCF.Category CategoriaYProductosPorId(int cat)
    {
        return base.Channel.CategoriaYProductosPorId(cat);
    }
    
    public ServiciosWCF.Order PedidoPorCliente(string Cliente, int Pedido)
    {
        return base.Channel.PedidoPorCliente(Cliente, Pedido);
    }
    
    public ServiciosWCF.Order[] PedidosPorCliente(string Cliente)
    {
        return base.Channel.PedidosPorCliente(Cliente);
    }
    
    public ServiciosWCF.Category CategoriaPorIDConErrores(int IdCategoria)
    {
        return base.Channel.CategoriaPorIDConErrores(IdCategoria);
    }
    
    public ServiciosWCF.Category CategoriaPorIDconPausa(int IdCategoria, int segundos)
    {
        return base.Channel.CategoriaPorIDconPausa(IdCategoria, segundos);
    }
    
    public int IncrementaContador()
    {
        return base.Channel.IncrementaContador();
    }
    
    public object[][] StockProductos(int IdCategoria)
    {
        return base.Channel.StockProductos(IdCategoria);
    }
}
